name: Build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Generate requirements.txt
        run: |
          pip install --user pipreqs
          ~/.local/bin/pipreqs . --force --encoding=utf8

      - name: Create or update branch
        run: |
          git checkout -B update-requirements
          git add requirements.txt
          git commit -m "Auto-update requirements.txt" || echo "No changes to commit"
          git push origin update-requirements --force

      - name: Check for new commits
        run: |
          if git diff --quiet main..update-requirements; then
            echo "No new commits to create a pull request."
            exit 0
          fi

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $GITHUB_TOKEN | gh auth login --with-token

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "Update requirements.txt" --body "This is an automated pull request to update requirements.txt" --base main --head update-requirements

  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Dep
        uses: zehengl/refresh-python-dependency@v0.4.2

      - name: Build and Release
        uses: kentsx/Python2Exe@v1.1.1
        with:
          main: main
          exe_name: "IS Subtitled"
          artifact: false
          release: true
