# this is a example for action taking when version.py in main branch changed only.
on: 
  workflow_dispatch:



jobs:
  
  
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Dep
        uses: zehengl/refresh-python-dependency@v0.4.2

      - name: Build and Release
        uses: kentsx/Python2Exe@v1.1.1
        with:
          main: main
          exe_name: 'IS Subtitled'
          artifact: false
          release: true
          token: ${{ secrets.TOKEN }}

